import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import styles from "../styles/Home.module.css";
import HeroSection from "../Components/HeroSection/HeroSection";
import AiBot from "../Components/AiBot/AiBot";

export default function Home() {
  useEffect(() => {}, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Ai Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AiBot />
    </div>
  );
}
